### ISSUE TITLE
Failed to resolve dependencies 

### ISSUE THREAD

**Issue by pykaso** [joshuawright11/papyrus#15]
Hi I have a problem with the latest version 

Dependencies could not be resolved because package 'papyrus' is required using a stable-version but 'papyrus' depends on an unstable-version package 'swift-syntax' and 'core' depends on 'papyrus' 0.5.0..

**Comment by joshuawright11** [comment]
Thanks for raising this - it looks like SwiftSyntax was updated yesterday with breaking changes. Will need to add those and ship a new release.

**Comment by joshuawright11** [comment]
Alright this is fixed with v0.5.1.
