### ISSUE TITLE
Invalid request URL when baseURL is missing trailing `/`

### ISSUE THREAD

**Issue by rraphaeldev** [joshuawright11/papyrus#18]
# Description

Initializing a `Provider` with a `baseURL` without a trailing `/` will produce a request with a malformed URL.

# How to reproduce

```swift
@API
protocol Github {
    @GET("/users/:username/repos")
    func getRepositories(username: String) async throws -> Response
}

let provider = Provider(baseURL: "https://api.github.com")
let github = GithubAPI(provider: provider)
let response = try await github.getRepositories(username: "alchemy-swift")
```

The built request will have an URL with a missing `/`:
```
https://api.github.comusers/alchemy-swift/repos
```

**Comment by joshuawright11** [comment]
Thanks for the callout @rraphaeldev 🙏 

Fixed in https://github.com/joshuawright11/papyrus/commit/0c9a903c43416c502a5f32981c3716cbdecc3094
