### ISSUE TITLE
Allow returning `Data` as a response type

### ISSUE THREAD

**Issue by sbhhbs** [joshuawright11/papyrus#20]
I tried writing "Data" as return type, but I got the response is not JSON as error. Is there any way to add a custom decoder or any other better way to do a binary file download request?

**Comment by joshuawright11** [comment]
Right now you could just return a `Response` and access the `body` field. See [accessing the raw response](https://github.com/joshuawright11/papyrus#accessing-the-raw-response).

But I also think that there's a valid case for special-casing Data so it just returns the body, if it exists. I'll update the title of this ticket and aim to add it soon

**Comment by joshuawright11** [comment]
This is now added with #30. 

Thanks for the request @sbhhbs!
