### ISSUE TITLE
Void return value support

### ISSUE THREAD

**Issue by winddpan** [joshuawright11/papyrus#22]
Sometimes we just make API calls to report data without caring about the API response.

```swift

@POST("user/openApp")
func openApp() async throws -> Void

==>

func openApp() async throws -> Void {
    let req = builder(method: "POST", path: "user/openApp")
    let res = try await provider.request(req)
    return try res.decode(Void.self, using: req.responseDecoder)  // <- Error: Type 'Void' cannot conform to 'Decodable'

}

```

**Comment by joshuawright11** [comment]
Good catch - currently it handles `func openApp() async throws` but I didn't consider an explicit `-> Void`.

Fixed in https://github.com/joshuawright11/papyrus/commit/f7374c9f2a392feaf92281f5986c9db35b2b29fc
