### ISSUE TITLE
PapyrusAlamofire not working

### ISSUE THREAD

**Issue by F0x1d** [joshuawright11/papyrus#34]
Macro generated API struct tries to access `Papyrus.Provider`, but if we use `PapyrusAlamofire`, then we should access `PapyrusAlamofire.Provider`.

So, i just get:
<img width="244" alt="image" src="https://github.com/joshuawright11/papyrus/assets/39910552/9112f11a-370f-4c43-8ecf-5cbfadfbfc73">

Generated macro:
<img width="476" alt="image" src="https://github.com/joshuawright11/papyrus/assets/39910552/7506c7e0-d7d9-4e8a-a4e8-ead6910820b2">

**Comment by joshuawright11** [comment]
Thanks for the report @F0x1d 🙏  - fixed in v0.6.3
