### ISSUE TITLE
Unable to build project and apply custom JSON encoder and decoder

### ISSUE THREAD

**Issue by F0x1d** [joshuawright11/papyrus#41]
I've just updated to Papyrus `v0.6.5` and get the following error:
<img width="270" alt="image" src="https://github.com/joshuawright11/papyrus/assets/39910552/09f7f791-bf29-4edb-883e-193f674bac45">

Macro expansion:
<img width="1043" alt="image" src="https://github.com/joshuawright11/papyrus/assets/39910552/9f4a5f97-cbff-409b-9273-238467061345">

Looks like because of this change:
<img width="608" alt="image" src="https://github.com/joshuawright11/papyrus/assets/39910552/9ab8609c-aa01-4584-8b15-530c574cbafc">

BTW, i have JSON applied:
```swift
@JSON(
    encoder: Container.shared.jsonEncoder(),
    decoder: Container.shared.jsonDecoder()
)
```

But according to macro expansion this is not used anywhere or maybe i don't see something?

**Comment by joshuawright11** [comment]
Sorry about that - was experimenting with something and didn't remove. Fixed in `v0.6.6`.
