### ISSUE TITLE
Log Failed Request cURL

### ISSUE THREAD

**Issue by lutes1** [joshuawright11/papyrus#43]
Curl's are very helpful to investigate failing requests in postman

**Comment by joshuawright11** [comment]
Great idea - are you thinking something like a debug string that prints a cURL string for copy paste?

Curious if there's any prior art you're thinking of.

**Comment by lutes1** [comment]
Yes, we could print a curl string to the console that would describe the failed request. 

The best way would be to have a request interceptor that would do just that. During development we could enable it for any request just to observe and compare the requests.

Inspiration: https://pub.dev/packages/curl_logger_dio_interceptor

**Comment by joshuawright11** [comment]
This is released in `v6.10.0`
